[package]
name = "ctfr"
version = "0.1.0"
edition = "2021"
description = " Optimized CTFd written with Rust & HTMX "
license = "GPL-3.0"
homepage = "https://github.com/MNThomson/CTFr"

[dependencies]
axum = { version = "0.6" }
tokio = { version = "1.34", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = { version = "0.1", features = ["attributes"] }
anyhow = "1.0.75"
