version: '3'

services:
  postgres:
    image: rapidfort/postgresql
    container_name: postgres_database
    restart: always
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: database
    ports:
      - 5432:5432


volumes:
  postgresql_data:
    driver: local

