[alias]
t = "nextest run"
r = "rp"
rr = ["watch", "-c", "-x", "run --release"]
rp = ["watch", "-c", "-x", "run --features sqlite --no-default-features"]
rs = ["watch", "-c", "-x", "run --features sqlite --no-default-features"]
c = ["watch", "-c", "-x", "clippy --all-targets"]
