[alias]
t = "nextest run"
r = "rp"
rp = ["watch", "-c", "-x", "run --profile dev-fast"]
rs = ["watch", "-c", "-x", "run --profile dev-fast --features sqlite --no-default-features"]
rr = ["watch", "-c", "-x", "run --release"]
c = ["watch", "-c", "-x", "clippy --all-targets"]
